### ISSUE TITLE
Wish list for the ingest inspector

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4532]
A non-exhaustive list of things I'd fix if I had the time:

- [ ] In the list of ingest events, add the date of an event as the `title` attribute
- [ ] Make the refreshing a bit less annoying – possibly polling an endpoint for "is updated"?
- [ ] Include a callback hostname
- [ ] When you enter an ingest ID and press enter, actually load the ingest – like a form would
- [x] Give a list of up to ten most-recently completed ingests
- [ ] Only highlight failures if the overall ingest is failed
- [ ] Change the colour of an emoji favicon based on the ingest status
- [ ] Host it at storage.wellcomecollection.org/ingests

From Ashley:

- [x] Render timestamps in the local timezone
- [ ] Highlight if an item is stalled or waiting to be retried
- [x] Make callbacks more obvious
- [ ] Is the storage service cold or warm right now?

**Comment by aray-wellcome** [comment]
Off the top of my head...I hope they make sense. 

1. Can the time stamp be fixed? 
It's an hour behind for BST and gets a bit confusing. 

2. Is there any way to expose if an item is stalled to be retried in the storage service later? 
From my side, I just see an item sitting at accepted or unpacking started and nothing happens for hours and when I ask why it's usually because it's waiting to retry later. 

3. More visually obvious callback status
Even though an item is marked as successfully ingested and goes green, the callback status may still be processing. The callback status is an important part for the Goobi workflow, can we call more attention to it visually when it's processing and successfully finished somehow?

4. Status
I know the storage service has to "warm up" in the morning and so it can be pretty slow processing a few items on quiet days. Is there anyway to see how fast the storage service might be at any given time? Because I never can tell if there's something wrong or if it's behaving normally and just needs to "warm up"

**Comment by alexwlchan** [comment]
> 1. Can the time stamp be fixed?

Yes.

Currently the dates are rendered by the Python rendering engine; doing it in JavaScript would fix this.

> 2. Is there any way to expose if an item is stalled to be retried in the storage service later?

Hmm.

That one’s harder, because there’s a bunch of different ways an ingest might stall. Let me think about it.

> 3. More visually obvious callback status

I’ll give it some thought.

> 4. Status

I can probably come up with a “slow/fast” indicator.

**Comment by alexwlchan** [comment]
The timestamp is fixed; stalled ingests are exposed in the daily reporter; pending callback status is highlighted blue.

Closing as “good enough for now”.
