### ISSUE TITLE
Figure out how to scale and place pipeline tasks on EC2 instances with shared storage

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/platform#4696]
This is in service of updating https://github.com/wellcomecollection/docs/tree/master/rfcs/021-data_science_in_the_pipeline to better handle multiple inferrer services

**Comment by alexwlchan** [comment]
Possibly some of the Archivematica infrastructure would be useful: https://github.com/wellcomecollection/archivematica-infrastructure

There's a persistent EBS volume attached to an instance, and then ECS tasks get scheduled on that instance.

Those all run on one big instance because Archivematica is super sensitive to filesystem latency, and EFS split across multiple hosts caused issues – the inferrer might be more tolerant of that.

Note there's a limit of how many tasks you can run on a single EC2 instance (constrained by Elastic Network Interfaces).

**Comment by jamieparkinson** [comment]
That's very helpful, thank you! Looks like EFS just isn't suited to scratch-style nonpersistent shared storage so (not-necessarily-persistent) EBS will probably be the first port of call
