### ISSUE TITLE
Improvements to image search relevancy

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4896]
Now that we have a bit more data from source works on images, we should look into porting some of the relevance improvements on catalogue search to image search.

We should make sure that image search is properly tracked in search analytics and run these improvements as tests, like we did for catalogue search.

Step one is to generate hypotheses for which search techniques we think will improve image search, along with making sure all required analytics is in place. Then we can start to make changes.

**Comment by harrisonpim** [comment]
From the chat with @alicerichmond today:

### broad insights about image search
- image searches are typically broader
- people often search by concept

### what kind of problems do people have with image search
- people _are_ finding stuff, but they then struggle to refine/steer their search
- more control needed, just like catalogue search a few months ago
- it's also difficult to discern how the images are related to one another, and/or to the researcher's query

### intentions we should be matching
- "looks like an xray, but should be related to vaccines"
- "anything from sweden"
- "anything related to medicine chests"
- "photograph or scan of cells"

**Comment by alicerichmond** [comment]
### **A couple of observed responses from users about image search intentions**

"I am going to try funery urn, I have in mind an object which I know is there, which is in the collection, but I think I already know it wont come up here. I mean that is another example of a funery reliquy but I expect that wouldnt come on the first page, when I search, I mean it is not so many results but yeah. Just seeing if maybe the search is too broad

Yep and it looks like it is bringing back things that arent really related to, well they are related to urns in a way because they are to do with funerals but it is not really returning things are funery urns as a kind of initial result"

"if I search for.. Trepanned skulls, it might all be examples that I have already mentioned. I guess here this is one thing actually which is where I would be searching for Trapanned skulls, we used to have a really good one in medicine man and I guess first of all the first entry, is not a trepanned skull, it is an instrument for Trepanning skull and I would expect that the search “Treppaned skulls” would actually bring those up, I dont think there is a way of having an exact phrase though so it would be nice to be able to have the exact phrase first, because often looking for a specific thing that I know is there and there is 1300 results because there could be any number of trepan, trephinating things, but I am looking for a skull, not any of these one"

"So we usually go with a theme, so for example for the next exhibition after the following on, we can search for eyes, ocular, just all the keywords around what we think the exhibition will have in it and also we will have a look at the library next and see what is in the books, and I have gone into the library and got books and used those images too. "

"it's quite tricky because it's not clear straight off if you're looking at work by this artist or what, how that tagging is associated with it."

### **Responses regarding image search filtering:** 

"And how can I see if all of these things are by Odra Noel? Cant filter by artist name, no? Right now might be useful, to be honest, because how do you know if this works by the person or if they just associate with them in another way or I don't know who that is."

"**Are there times when you struggle to find things that you are looking for?**

Yes

**Do you have any examples of that?**

When you kind of, I think using keyword combinations, sometimes you will put in a keyword or two or just a keyword and you get 500 pages of results, currently I have the time but not normally. It is hard to exclude images but if you have too many results sometimes it gives the keyword tagging of the images which is always going to be an issue as we have so many objects"

**Comment by jamesgorrie** [comment]
## Add examples to `rank_eval`

- Make sure some events are on the first page


## Query 

- Boost on concepts
- Minimum should match 
- Look into language stemming
- boost IDs much more heavily and use whitespace analyzer
