### ISSUE TITLE
Use private VPC link between Elastic Cloud and our pipeline

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4949]

**Comment by kenoir** [comment]
In order to reduce pipeline costs we should route requests via a VPC endpoint, rather than via our NAT gateways.

TODO:
- [ ] Configure access credentials using existing scripts
- [ ] Ensure access/credentials are configurable in the pipeline stack
- [ ] Run a test reindex demonstrating that requests are being routed correctly

**Comment by alexwlchan** [comment]
Quick back-of-the-napkin calculation: the works index is ~30GB, and the images index is ~20GB. Total is ~50GB.

We know a reindex will typically ingest the same Work/Image multiple times (due to embedding relations, merging, etc.) so the data we sent over NAT Gateway during a reindex was probably several times that. Then we suck out the complete contents of the works index at least once a day (for snapshots) and as individual queries (for the API).

Meanwhile, the logging data from across the entire platform in a week with two reindexes is only ~60GB.

I've got PrivateLink working for the catalogue services, but I'm going to skip doing it for logging for now. It's a bigger infra change for a smaller saving.
