### ISSUE TITLE
Thumbnails missing for digitised archives and manuscripts

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4962]
It doesn't look like we're adding thumbnails for digitised archives and manuscripts. I suspect this might be merger related, ie we add them to the Sierra work and then override that work with the one from Calm.

In any case, we should be adding thumbnails to open digitised works from Calm. Some examples:

https://wellcomecollection.org/works?query=Ms&workType=h&items.locations.type=DigitalLocation

https://wellcomecollection.org/works?query=Receipt+book&workType=h&items.locations.type=DigitalLocation

Same rules should apply, taking the title page if it's marked up.

**Comment by alexwlchan** [comment]
@jtweed I've had a look at the associated merger code and worked out what's going on.

If if the access condition is "Open", you get a thumbnail. If the access condition is "Open with Advisory", you don't get a thumbnail. We have an explicit test for that behaviour, so I assume this is by design.

Should we also display thumbnails for open-with-advisory content?

https://wellcomecollection.org/works?query=Ms&workType=h&items.locations.type=DigitalLocation

<table><tr><th>Work</th><th>Access condition</th><th>Has thumbnail?</th></tr>
<tr><td><a href='https://wellcomecollection.org/works/bum7tkn6'>bum7tkn6</a></td><td>Open with Advisory</td><td>
</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/ccxdj4v6'>ccxdj4v6</a></td><td>Open with Advisory</td><td>
</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/ncb9cnp7'>ncb9cnp7</a></td><td>Open with Advisory</td><td>
</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/gavf2n44'>gavf2n44</a></td><td>Open with Advisory</td><td>
</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/jtvpzz37'>jtvpzz37</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/t2x7sgck'>t2x7sgck</a></td><td>Open with Advisory</td><td>
</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/e9r2fxfk'>e9r2fxfk</a></td><td>Open with Advisory</td><td>
</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/c2mcdvzv'>c2mcdvzv</a></td><td>Open with Advisory</td><td>
</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/cz2y5dma'>cz2y5dma</a></td><td>Open with Advisory</td><td>
</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/dkz6cx2t'>dkz6cx2t</a></td><td>Open with Advisory</td><td>
</td></tr>
</table>

https://wellcomecollection.org/works?query=Receipt+book&workType=h&items.locations.type=DigitalLocation:

<table><tr><th>Work</th><th>Access condition</th><th>Has thumbnail?</th></tr>
<tr><td><a href='https://wellcomecollection.org/works/eybhw479'>eybhw479</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/h3xk7wbg'>h3xk7wbg</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/nfws4xvj'>nfws4xvj</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/p4b5jpmj'>p4b5jpmj</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/zub84cwr'>zub84cwr</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/k7q4rvq7'>k7q4rvq7</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/uy8paceu'>uy8paceu</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/qen4w82y'>qen4w82y</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/yxbw28gp'>yxbw28gp</a></td><td>Open</td><td>
✅</td></tr>
<tr><td><a href='https://wellcomecollection.org/works/athgku89'>athgku89</a></td><td>Open with Advisory</td><td>
</td></tr>
</table>

**Comment by pollecuttn** [comment]
Re open with advisory, see https://www.notion.so/Digitised-content-access-control-Q1-2020-Q2-2021-fa5b296f9507455ab407faeaf5f40a57#8bf12e7943254b5b9de18cda4b1bfe29, linked to from https://github.com/wellcomecollection/wellcomecollection.org/issues/5470

**Comment by tomcrane** [comment]
Just a note that thumbnails are available via DLCS for the (old) `Requires Registration` access condition, but only the 100px and 200px thumbnails; the 400 and 1024 thumbs are only for `Open` images. This is dictated by thumbnail policy.

**Comment by jtweed** [comment]
Ah, there might not have been an issue here then. When I raised the ticket, the open items did not have thumbnails, so I assume this has been fixed by a recent reindex bringing in feature work from before Christmas.

To confirm, it's been agreed with C&R that open with advisory should not have thumbnails.

**Comment by alexwlchan** [comment]
> When I raised the ticket, the open items did not have thumbnails, so I assume this has been fixed by a recent reindex bringing in feature work from before Christmas.

Ah yeah, changing the prod pipeline this week would have brought in quite a lot of changes.
