### ISSUE TITLE
DDS should follow fetch.txt in storage bags

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#5068]
This picks up a [discussion from last year](https://digirati.slack.com/archives/CBT40CMKQ/p1600330545305600?thread_ts=1600269914.301100&cid=CBT40CMKQ).

At the moment the DDS doesn't know about fetch.txt. It gets the storage manifest, then expects to find every file it needs listed there, even if they are across different versions.
So far, this works. 

For example - https://iiif-test.wellcomecollection.org/dash/Peek/StorageManifest/b16799100
All the files mentioned in the METS are present and listed in the storage manifest. It has mixed `v1/` and `v2/` paths.

But here's one that doesn't work:

https://iiif-test.wellcomecollection.org/dash/Peek/StorageManifest/b16676166
It has mixed paths, but doesn't have the MPEG file `objects/0055-0000-4078-0000-0-0000-0000-0.mpg`

As far as the DDS is concerned, this file is missing.

This means we need to implement fetch.txt; the DDS needs to follow fetch.txt when building the **_map_** of file storage for a b number.

**Comment by alexwlchan** [comment]
@tomcrane I can't see that discussion; the link takes me into the Digirati Slack.

Looking at the fetch.txt for that bag won't help you – the whole point of the storage manifest is that it collates entries from the fetch.txt so clients don't have to. If a file doesn't appear in the manifest, it doesn't appear anywhere in that version of the bag.

Here's the contents of fetch.txt in that bag:

```
s3://wellcomecollection-storage/digitised/b16676166/v1/data/b16676166_0001.xml - data/b16676166_0001.xml
```

The MPG file is in a previous version of the bag, but you won't find that by looking in fetch.txt.

**Comment by alexwlchan** [comment]
(It's not obvious to me from the thread why the MPG isn't in the latest version of the bag, even if it's via fetch.txt.)

**Comment by tomcrane** [comment]
This is good and bad. Good - because the storage manifest _is_ the collated version of the assets for that b number, so the DDS can do everything from that one source, as it has been doing. Bad - because why is b16676166 missing its MPEG?

Here's another example:
https://iiif-test.wellcomecollection.org/dash/Peek/StorageManifest/b1665836x

That has even less present in its v3.

**Comment by alexwlchan** [comment]
This is probably a question for Ashley/the digitisation team – this looks like something weird is going on in the workflow that builds the bags.

**Comment by tomcrane** [comment]
@aray-wellcome any ideas?

**Comment by aray-wellcome** [comment]
Ok I can tell you what's going on in these two examples. 

 b16676166_0001 was ingested the first time into Preservica from Goobi in 2014. In October 2019 Harkiran tried to add a pdf transcript to it in b16676166_0002 which is why there's only a PDF in it. So that'd be expected for v2 to not have a mpg in it, it's actually an MM addition. It does not look like this addition worked so it will need reingested in the new a/v workflow. 

In b1665836x_0001, it was migrated over to the storage service which made v1. The video wasn't playing though. Harkrian tried to re-ingest the mpg in v2 but the mpg is corrupted so it needs to be re-digitized. In v3, a blank fetch.txt was sent through to stop DDS from seeing the previous mpgs in the storage service so the broken mpg wasn't served for access. This just needs to be re-ingested completely fresh in the new a/v workflow.

**Comment by tomcrane** [comment]
To be sure...

> So that'd be expected for v2 to not have a mpg in it, it's actually an MM addition.

The storage manifest _should_ be listing the mpg in its v1 incarnation; I don't need to look anywhere other than the one and only storage manifest to discover its location in S3. Normally this would be the case but the storage manifest is wrong in this case, for some reason.

**Comment by aray-wellcome** [comment]
For b16676166_0001 yes, the mpg should be in its v1 incarnation. I can see the mpg in the bag of v1. 

I have a feeling because the mpg was migrated and then the pdf was attempted to be added to it post-migration that that may be where something went awry. But for the majority of the a/v it should've all just been migrated together and we haven't really touched it since, except for trying to update some access and license statuses.

**Comment by tomcrane** [comment]
Closing this as I don't think there are any DDS changes needed.
