### ISSUE TITLE
Audit how we log PII in the identity services

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5166]
See discussion on https://github.com/wellcomecollection/identity/pull/125

There are debug logs in the identity services that will log some PII-looking data into the Kibana logging cluster. (PII = [Personally identifying information](https://en.wikipedia.org/wiki/Personal_data).)

We should investigate exactly what's being logged there, and decide what we want to do with it.

- [x] identity repo (https://github.com/wellcomecollection/identity/pull/169)
- [x] requests API
- [ ] identity services in the dotorg repo

**Comment by kenoir** [comment]
I do not believe the identity-api logs to the logging cluster (though the requesting service will), the lambdas that make it up log to CloudWatch logs which suffers similar issues though.

Any PII in the logging cluster is out because it is essentially open to anyone with a Wellcome account. We could restrict access (and similarly to CloudWatch), but I would prefer to audit anything we are logging and exclude/anonymize it before we do.

**Comment by alexwlchan** [comment]
I've had a look, and I can't see us logging (or retrieving) patron information in the current requests API. We'll need to be careful when we do the requesting reporting, but that doesn't exist yet.
