### ISSUE TITLE
Review the pregenerated sizes in DLCS and the images we display on wc.org/images

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5338]
Currently DLCS hasp regenerated sizes for 100,200,400,1024, and then creates other sizes on demand.

It might be useful to pregenerate images for other sizes we use a lot on wc.org, e.g. 2048px wide for 2x displays.

We'd need to review what sizes we're using on wc.org and then get them into DLCS. We may need to backfill (https://github.com/dlcs/protagonist/issues/126, https://github.com/dlcs/protagonist/issues/66).

**Comment by tomcrane** [comment]
My preferred approach for this is the auto-backfill.

 - Thumbnails are created at ingest time according to the policy associated with the ingested image, or the default policy.
 - We should accommodate https://github.com/dlcs/protagonist/issues/66 because the current wc.org work page is a real world use of it (only width constrained).
 - If a request for a thumbnail arrives at the thumbnail app or orchestrator and the thumbnail is NOT present in S3 but should be present according to the policy currently associated with the image, the thumbs will be reprocessed to match the policy (ensure all thumbs required by the policy are present AND delete any that are not)
 - We don't have to do a bulk update of all the thumbs when a policy changes because the above behaviour will auto-backfill, at the expense of a delay on first hit.
 - If you really need to ensure a large number of thumbs are pre-filled to avoid that delay, then you can script something to request the desired size for them all (make an HTTP GET for the thumb), we don't need an extra API operation to rebuild and we don't need to rebuild thumbs on a change to the configured policy in the DB, which could have big cascading update issues.

**Comment by tomcrane** [comment]
Further to the above comment - while we don't have stats from GA for the transition from large static image to tiled, we could determine this in the DLCS orchestrator with some specific logging and gathering data over time. So we can still fine tune the allocation of resources between the two modes of image interaction.

@jennpb ^

**Comment by tomcrane** [comment]
Summary of options (from Slack, plus more)

1) implement the thumbnail proposal (linked above) - where we allow the DLCS to generate fixed-width but variable height thumbs. This would be super-fast for users, but has storage costs implications - we'd be storing more GB of thumb jpegs than the original JP2s.

2) In the new DLCS, these large images are served by Cantaloupe directly streaming the source JP2 from the storage service rather than orchestrating it. We did some work on improving Cantaloupe itself here, but there's more that could be done. And we can also look at increasing the AWS resources allocated to the service that does this streaming (SpecialServer).

2a) If Orchestrator knows that the image is on the orchestration volume (e.g., someone has recently requested tiles), then forward to regular Cantaloupe not SpecialServer

3) We could change the behaviour of the orchestrator so that it understands the responsive image configuration of the works page and will not send matching width requests to SpecialServer, and instead send them down the normal cantaloupe path where the image is orchestrated to fast disk.

**Comment by tomcrane** [comment]
If 1, then we'll need https://github.com/dlcs/protagonist/issues/66 and https://github.com/dlcs/protagonist/issues/126

**Comment by tomcrane** [comment]
Some supporting arguments for case 1.

A recent client of ours has a lot of print-heavy materials. They also liked the ideas in https://medium.com/digirati-ch/progressive-enhancement-digital-objects-and-the-exploded-viewer-b0594d7bbb52. They also like the way the Wellcome work page presents large static images in a vertical scroll.

Their current site uses PDFs, which have the nice features of scrollability, text-selectability and portability but give a poor user experience because of the initial long download time. Can we get the good affordances of PDF but _from a IIIF Manifest_? The Wellcome work page is doing this to some extent.

Caveats - the following is not optimised for different screen sizes and uses my amateurish CSS skills. the scrolling interaction for known JPEG sizes is the thing being investigated (and also the accessibility of the HTML but that's a separate issue).

https://st-louis-fed-exploded-viewer.azurewebsites.net/wellcome/canvasv/b2101310x/b2101310x_0029.jp2?script_on=true

https://st-louis-fed-exploded-viewer.azurewebsites.net/fraser/canvasv/632173/632173_0_0056?script_on=true

On a fast internet connection this gives pretty good performance for scrolling through - and that's down to the images being pre-generated at the expected sizes.

We're also aiming for selectable text on the image surface, like a PDF with a text layer (and like this - https://st-louis-fed-exploded-viewer.azurewebsites.net/wellcome/canvas/b2101310x/b2101310x_0077.jp2?script_on=true&default_cp_text=true) but we haven't combined those two experiments yet.

**Comment by tomcrane** [comment]
From conversations two weeks ago we will be going with option 1.

As an introduction for our new starters we refined this issue together:

https://github.com/dlcs/protagonist/issues/66#issuecomment-1609800287

This will lead to some pretty awesome performance on the works page.

**Comment by kenoir** [comment]
Closing as tracked elsewhere.
