### ISSUE TITLE
Add subfield $j from 700 as contributor role

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5578]
MARC fields `100` and `700` (main and added entry personal names) can have a subfield `$j - Atribution qualifier (R)`.

This isn’t widely used in the catalogue, but it is used to give context to the named person’s relation to the object being described.

An example of this can be found on b1202594x:

https://wellcomecollection.org/works/c9tzn3ha

Where it’s not clear that the contributor is a follower of the name given, rather than the person themselves. This most closely maps to our existing `ContributionRole` on `Contributor`, which we can reuse for this subfield.

So in the example:

`700 1  Zurbarán, Francisco de,|d1598-1664,|jFollower of|0n 50015926`

Should appear in the API as: 

```json
{
  "agent": {
    "id": "w7r2dc4w",
    "label": "Zurbarán, Francisco de, 1598-1664",
    "type": "Person"
  },
  "roles": [
    {
      "label": "Follower of",
      "type": "ContributionRole"
    }
  ],
  "type": "Contributor"
}
```

This should be picked up automatically by the works page, as it already displays roles on contributors.

**Comment by alexwlchan** [comment]
I'm going to expand this out to all the contributor MARC tags we use (100/110/111/700/710/711) – it's only used once on 100/700, but quite a few more times on the other tags.

```
Counter({'110': 3, '111': 90, '700': 1, '710': 1, '711': 66})
```

**Comment by alexwlchan** [comment]
I think our current logic might be correct here, and we should fix this in the data instead.

This is the current logic:

* 100, 110, 700, 710 = get the contributor role from subfield $e
* 111, 711 = get the contributor role from subfield $j

This is a breakdown of when those subfields are used, based on MARC tag

<table>
<tr><th>MARC tag</th><th>only 'e'</th><th>only 'j'</th><th>both 'e' and 'j'</th></tr>
<tr><td>100</td><td>14,224</td><td>0</td><td>0</td></tr>
<tr><td>110</td><td>2,108</td><td>3</td><td>1</td></tr>
<tr><td>111</td><td>42</td><td>90</td><td>1</td></tr>
<tr><td>700</td><td>56,004</td><td>1</td><td>0</td></tr>
<tr><td>710</td><td>90,899</td><td>1</td><td>0</td></tr>
<tr><td>711</td><td>28</td><td>66</td><td>0</td></tr>
</table>

Given that this only affects five records:

b25333288
b24978966
b24811981
b1202594x
b28673475

I wonder if the correct change is actually to update those five records to make them consistent, rather than add code to our transformer?

**Comment by jtweed** [comment]
One for Nic in the first instance, from whom this came from initially.

**Comment by alexwlchan** [comment]
I've sent Vicky W an email to find out what the best approach is here.

**Comment by alexwlchan** [comment]
I've had an email from Vicky and Louise which clarifies the intended behaviour – we want $j for contribution role on 700 but not 100. I’m about to open a PR that adds this.

**Comment by alexwlchan** [comment]
I've triggered a one-off reindex for b1202594x, which should appear shortly.

**Comment by alexwlchan** [comment]
Done!
