### ISSUE TITLE
Find out more about a concept used to describe a work

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5585]
### User stories

As a researcher
I want to find out more about a subject, person or technique
So that I can decide if they are worth researching further

As a researcher
I want to find other works with the same subject, person or technique
So that I can find other things that might be relevant to my research

### Measures

- Total concept pages viewed
- Unique concept pages viewed
- Clickthrough to concept pages

### Acceptance criteria

- Concept pages for subjects, people and techniques
- Basic descriptive data to allow disambiguation (label and dates active)
- Subjects, people and techniques on works pages link to concept pages
- Pages use new design system and colour palette
- Analytics tracking in place for all measures

**Comment by rcantin-w** [comment]
Work was presented and discussed with @GarethOrmerod @jtweed and based off that, the development work will stop for this piece until a few things are re-explored in the mockups:
- Button copy; make it more generic?
- Hero/Header section: change its layout?
- How to we expose related subjects/people (or is this phase 2?)
- We're happy with the tabs, but how do they look on smaller devices/when there is more than two?

Dev discovery:
- Image section; maybe we want a grid instead of a scrollable one (see #5589 for the discovery ticket)

Other decisions from that meeting:
- Buttons need to get aligned with the new styles that are also getting suggested in the Access team, the ones in the mockups are suggestions and not what they'll actually look like. Need to see if we can use a darker shade first and a lighter one on hover.
- Sticking to one colour for now (I'll do yellow for now but it can be changed).
- If a section is empty, hide it completely

**Comment by rcantin-w** [comment]
Few tweaks still needed after talking to @jtweed (please correct if missing or misunderstood anything):
- Get analytics consult/integration (Raph to book a call with Jonathan and Tacey)
- Confirm what to put in generic description in hero, and in meta description ( @jtweed )
- Confirm about having pages only for Subjects (and not Contributors or Genre) ( @jtweed to check with Alex )
